#coding: utf-8 

import os

def cleanFrame(prjDir,filename):
	srcFile = os.path.join(prjDir+"\descode",filename+'.py')
	# open the file generated by wxformebuilder.
	ptrFile=open(srcFile,'r')
	fbGeneratedCode = ptrFile.read()
	fbGeneratedCode = fbGeneratedCode.replace('\t','    ')
	fbGeneratedCode = fbGeneratedCode.replace('m_','')
	ptrFile.close()
	# ----- Save src code
	outFile = os.path.join(prjDir+'\src',filename+'.py')
	
	if os.path.exists(outFile):
		ptrFile=open(outFile,"w")
	else:
		ptrFile=open(outFile,"w+")
		
	# write cleaned code to src folder.	
	ptrFile.write(fbGeneratedCode)
	ptrFile.close()

	return 'complete'
dirname = os.path.dirname(__file__)
prjDir = os.path.join(dirname,"..\\")
#prjDir = r"C:\Users\STarikUser\Documents\gif-viewer"
filename = "gifviewer"

print('Cleaning descode fiel: %s' % filename +'.py')
outStat = cleanFrame(prjDir,filename)
print('Clean descode file and save in src folder %s.' % outStat )



